version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src:/var/www
      - ./_docker/dev/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 3000:80
    depends_on:
      - app
    container_name: bot_nginx

  app:
    build:
      context: .
      dockerfile: _docker/dev/php/Dockerfile
    volumes:
      - ./src:/var/www
    container_name: bot_app
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./_db/postgres:/var/lib/postgresql/data
      - ./_docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5434:5432
    container_name: bot_db
